apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: signaltrade
  namespace: argocd
spec:
  description: SignalTrade staging GitOps applications
  sourceRepos:
    - https://github.com/KTCloud-Crypto/signaltrade-gitops.git
  destinations:
    - namespace: signaltrade-staging
      server: https://kubernetes.default.svc
    - namespace: signaltrade-node-metrics-staging
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: storage.k8s.io
      kind: StorageClass
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
