global:
  environment: staging
  namespace: signaltrade-staging
secret:
  commonKey: signaltrade/staging/common
  databaseKey: signaltrade/staging/database
# 서비스 CI가 검증된 immutable tag 또는 digest를 이곳에 반영합니다.
apis:
  identity: {tag: 44602080acdbce3935234f6c96221217de2b165b, replicas: 2}
  strategy: {tag: 6c64d19a15ad48e0afac1e43f627f78024a8c263, replicas: 2}
  trading: {tag: 4d9a240ff8e4e573a68b3ad0d23c5e0576feddf3, replicas: 2}
  portfolio: {tag: 4f7c4d714dda616a01a9b1c6ed7cc67a6ea9481b, replicas: 2}
workers:
  messaging: {tag: 90565dc022f81c1373e80ff8995dc333bc3847e6, replicas: 1}
  strategy: {tag: 6c64d19a15ad48e0afac1e43f627f78024a8c263, replicas: 1}
  trading: {tag: 4d9a240ff8e4e573a68b3ad0d23c5e0576feddf3, replicas: 1}
  portfolio: {tag: 4f7c4d714dda616a01a9b1c6ed7cc67a6ea9481b, replicas: 1}
  notification: {tag: c2b0ee89402a4f4a196908ef3e03b123190c9a79, replicas: 1}
migration: {tag: 7600af5f909e7ef7f4d622889444d0c3ad25606c}
ingress: {enabled: true}
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
