global:
  environment: production
  namespace: signaltrade-production
secret:
  commonKey: signaltrade/production/common
  databaseKey: signaltrade/production/database
  serviceKeys:
    identity: signaltrade/production/identity
    notification: signaltrade/production/notification
ingress:
  enabled: false
  loadBalancerName: signaltrade-production
apis:
  identity: {tag: 54887c09f1934cad641d8069fa0dbae835c976e3, replicas: 2}
  strategy: {tag: 63e0be3582032c345b4de7a653df033213d38904, replicas: 2}
  trading: {tag: a78134c019fbc25ab13581e00b3a2a8d864104a1, replicas: 2}
  portfolio: {tag: a8379c280f7b258ef7c18d01ddfd0bd0b2b0ea32, replicas: 2}
workers:
  messaging: {tag: 90565dc022f81c1373e80ff8995dc333bc3847e6, replicas: 1}
  strategy: {tag: 63e0be3582032c345b4de7a653df033213d38904, replicas: 1}
  trading: {tag: a78134c019fbc25ab13581e00b3a2a8d864104a1, replicas: 1}
  portfolio: {tag: a8379c280f7b258ef7c18d01ddfd0bd0b2b0ea32, replicas: 1}
  notification: {tag: c2b0ee89402a4f4a196908ef3e03b123190c9a79, replicas: 1}
migration: {tag: 6e00ed3f9e7a9574f496c55deb08fa0b90e73d42}
