global:
  environment: production
  namespace: signaltrade-production
secret:
  commonKey: signaltrade/production/common
  databaseKey: signaltrade/production/database
  serviceKeys:
    identity: signaltrade/production/identity
    notification: signaltrade/production/notification
ingress:
  enabled: false
  loadBalancerName: signaltrade-production
apis:
  identity: {tag: replace-with-release-sha, replicas: 2}
  strategy: {tag: replace-with-release-sha, replicas: 2}
  trading: {tag: replace-with-release-sha, replicas: 2}
  portfolio: {tag: replace-with-release-sha, replicas: 2}
workers:
  messaging: {tag: replace-with-release-sha, replicas: 1}
  strategy: {tag: replace-with-release-sha, replicas: 1}
  trading: {tag: replace-with-release-sha, replicas: 1}
  portfolio: {tag: replace-with-release-sha, replicas: 1}
  notification: {tag: replace-with-release-sha, replicas: 1}
migration: {tag: replace-with-release-sha}
